options:
  docker: true

pipelines:
  tags:
    6.*:
      - step:
          name: Trigger Wordpress build
          script:
            - pipe: atlassian/trigger-pipeline:5.0.0
              variables:
                BITBUCKET_USERNAME: $PIPELINES_TRIGGER_USER
                BITBUCKET_APP_PASSWORD: $PIPELINES_TRIGGER_PASS
                BRANCH_NAME: "6.x"
                ACCOUNT: "iconagency"
                REPOSITORY: "lagoon-wordpress"
          caches:
            - docker
