# Add some custom tooling that isn't in the Lando Lagoon beta yet.
tooling:
  pull:
    cmd: "/lagoon-tools/assets/wordpress/5x/lando/lagoon-pull.sh"

  push:
    cmd: "/lagoon-tools/assets/wordpress/5x/lando/lagoon-push.sh"
